# Directorios
music_directory     "~/Música"
playlist_directory  "~/.local/share/mpd/playlists"
db_file             "~/.local/share/mpd/database"
log_file            "~/.local/share/mpd/mpd.log"
pid_file            "~/.local/share/mpd/mpd.pid"
state_file          "~/.local/share/mpd/mpdstate"

# Red
bind_to_address     "127.0.0.1"
port                "6600"

# Audio via PipeWire
audio_output {
    type    "pipewire"
    name    "PipeWire"
}

# Normalización de volumen
replaygain          "auto"

# Salida para visualizador cava/ncmpcpp
audio_output {
    type            "fifo"
    name            "Visualizer"
    path            "/tmp/mpd.fifo"
    format          "44100:16:2"
}
