# Catppuccin Mocha para btop

theme[main_bg]="#1e1e2e"
theme[main_fg]="#cdd6f4"
theme[title]="#cdd6f4"
theme[hi_fg]="#89b4fa"
theme[selected_bg]="#45475a"
theme[selected_fg]="#cdd6f4"
theme[inactive_fg]="#6c7086"
theme[graph_text]="#bac2de"
theme[meter_bg]="#313244"
theme[proc_misc]="#cba6f7"
theme[cpu_box]="#89b4fa"
theme[mem_box]="#a6e3a1"
theme[net_box]="#89dceb"
theme[proc_box]="#cba6f7"
theme[div_line]="#45475a"

theme[temp_start]="#a6e3a1"
theme[temp_mid]="#f9e2af"
theme[temp_end]="#f38ba8"

theme[cpu_start]="#89b4fa"
theme[cpu_mid]="#cba6f7"
theme[cpu_end]="#f5c2e7"

theme[free_start]="#89dceb"
theme[free_mid]="#94e2d5"
theme[free_end]="#a6e3a1"

theme[cached_start]="#b4befe"
theme[cached_mid]="#89b4fa"
theme[cached_end]="#74c7ec"

theme[available_start]="#f9e2af"
theme[available_mid]="#fab387"
theme[available_end]="#eba0ac"

theme[used_start]="#cba6f7"
theme[used_mid]="#f5c2e7"
theme[used_end]="#f38ba8"

theme[download_start]="#89b4fa"
theme[download_mid]="#89dceb"
theme[download_end]="#94e2d5"

theme[upload_start]="#cba6f7"
theme[upload_mid]="#f5c2e7"
theme[upload_end]="#f38ba8"

theme[process_start]="#a6e3a1"
theme[process_mid]="#89b4fa"
theme[process_end]="#cba6f7"
