# ============================================================
# Apariencia
# ============================================================

default_border pixel 2
default_floating_border pixel 2

gaps inner 8
gaps outer 4

smart_gaps on
smart_borders on

font pango:Lexend 10

# Colores                  border     background  text       indicator  child_border
client.focused             $blue      $base       $text      $blue      $blue
client.focused_inactive    $surface0  $base       $subtext1  $surface0  $surface0
client.unfocused           $crust     $base       $overlay0  $crust     $crust
client.urgent              $red       $base       $red       $red       $red

output * bg ~/Imágenes/wallpaper.png fill

seat seat0 xcursor_theme Breeze_Light 24
