# ============================================================
# Teclado y touchpad
# ============================================================

input "type:keyboard" {
    xkb_layout latam
    repeat_delay 300
    repeat_rate 45
}

input "type:touchpad" {
    tap enabled
    natural_scroll enabled
    dwt enabled
    scroll_method two_finger
    click_method clickfinger
    accel_profile adaptive
    middle_emulation enabled
}
