# ============================================================
# Reglas de ventanas y workspaces
# ============================================================

assign [app_id="^foot$"] workspace number 1:term
assign [app_id="^foot-term$"] workspace number 1:term
assign [app_id="^firefox$"] workspace number 2:web
assign [app_id="^foot-music$"] workspace number 3:music
assign [app_id="^foot-music-ncmpcpp$"] workspace number 3:music
assign [app_id="^foot-music-ncspot$"] workspace number 3:music
assign [app_id="^foot-music-pyradio$"] workspace number 3:music
assign [app_id="^foot-files$"] workspace number 4:files
assign [app_id="^foot-system$"] workspace number 5:system

for_window [app_id="^foot-music$"] focus
for_window [app_id="^foot-music-ncmpcpp$"] focus
for_window [app_id="^foot-music-ncspot$"] focus
for_window [app_id="^foot-music-pyradio$"] focus
for_window [app_id="^foot-files$"] focus
for_window [app_id="^foot-system$"] focus

# Ventanas flotantes auxiliares
for_window [app_id="bluetui-floating"] floating enable
for_window [app_id="bluetui-floating"] resize set 760 430
for_window [app_id="bluetui-floating"] move position center
for_window [app_id="bluetui-floating"] focus

for_window [app_id="impala-floating"] floating enable
for_window [app_id="impala-floating"] resize set 760 430
for_window [app_id="impala-floating"] move position center
for_window [app_id="impala-floating"] focus

for_window [app_id="audio-floating"] floating enable
for_window [app_id="audio-floating"] resize set 760 320
for_window [app_id="audio-floating"] move position center
for_window [app_id="audio-floating"] focus

for_window [app_id="battery-floating"] floating enable
for_window [app_id="battery-floating"] resize set 620 460
for_window [app_id="battery-floating"] move position center
for_window [app_id="battery-floating"] focus
