# ============================================================
# Reglas de ventanas y workspaces
# ============================================================

assign [app_id="firefox"] workspace number 2
assign [app_id="foot-music"] workspace number 3
assign [app_id="pyradio-music"] workspace number 3

for_window [app_id="foot-music"] focus
for_window [app_id="pyradio-music"] focus

# Ventanas flotantes auxiliares
for_window [app_id="bluetui-floating"] floating enable
for_window [app_id="bluetui-floating"] resize set 760 430
for_window [app_id="bluetui-floating"] move position center
for_window [app_id="bluetui-floating"] focus

for_window [app_id="nmtui-floating"] floating enable
for_window [app_id="nmtui-floating"] resize set 760 430
for_window [app_id="nmtui-floating"] move position center
for_window [app_id="nmtui-floating"] focus

for_window [app_id="audio-floating"] floating enable
for_window [app_id="audio-floating"] resize set 760 430
for_window [app_id="audio-floating"] move position center
for_window [app_id="audio-floating"] focus

for_window [app_id="battery-floating"] floating enable
for_window [app_id="battery-floating"] resize set 760 430
for_window [app_id="battery-floating"] move position center
for_window [app_id="battery-floating"] focus
