# ============================================================
# Autostart
# ============================================================

exec_always ~/.local/bin/sway-autostart
exec_always ~/.local/bin/start-idle
