#!/usr/bin/env bash

exec foot \
  --app-id nmtui-floating \
  --title "Redes" \
  --override=main.font="JetBrainsMono Nerd Font:size=8.5" \
  --override=main.pad=6x4 \
  --override=colors.alpha=1.0 \
  --window-size-chars=76x20 \
  -e ~/.local/bin/nmtui-catppuccin
