title   Arch Linux (zen)
linux   /vmlinuz-linux-zen
initrd  /intel-ucode.img
initrd  /initramfs-linux-zen.img
options root=UUID=f0a05552-b72c-4acb-b5f5-385c81612743 rw quiet loglevel=3 i915.stolen_reserved_size=0
